[package]
name = "igloo_agent"
version = "0.1.0"
authors = ["Penguin <penguin@epenguin.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
igloo_core = {path = "../igloo_core"}